import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'

type View = 'home' | 'tasks' | 'discover' | 'compare'
type Preference = 'balanced' | 'noise' | 'battery' | 'lowest'
type IconName = 'arrow' | 'check' | 'chevron' | 'close' | 'external' | 'filter' | 'grid' | 'info' | 'plus' | 'search' | 'spark' | 'star' | 'target'
type Mission = { id: number; intent: string; budget?: number; preference: Preference; onlyInStock: boolean; version: number }
type Product = { id: string; title: string; brand: string; model: string; platform: string; tone: string; market: string; nativePrice: string; rmbPrice: number; fx: string; fxAsOf: string; updated: string; rating: number; reviews: number; stock: '有货' | '库存有限' | '暂无库存信息'; specs: string[]; why: string; tradeoff: string; image: string; gradient: string; url: string }
type Message = { id: string; role: 'user' | 'agent'; text: string; actions?: string[] }
type ChangeRecord = { id: string; summary: string; before: Mission; selectedBefore: string[]; resultBefore: number; resultAfter: number }
type TaskPhase = 'collecting' | 'shortlisting' | 'comparing'
type ShoppingTask = { id: number; mission: Mission; selected: string[]; messages: Message[]; latestChange: ChangeRecord | null; phase: TaskPhase; lastSurface: 'discover' | 'compare'; createdAt: string; updatedAt: string; updatedAtMs: number }

const products: Product[] = [
  { id: 'sony-xm5', title: 'Sony WH-1000XM5 无线降噪耳机', brand: 'Sony', model: 'WH-1000XM5', platform: 'Amazon', tone: 'amazon', market: '美国 · US', nativePrice: 'USD 299.00', rmbPrice: 2149, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '3 分钟前更新', rating: 4.8, reviews: 1240, stock: '有货', specs: ['主动降噪', '续航 30 小时', 'Bluetooth 5.2'], why: '降噪、续航与评分比较均衡。', tradeoff: '适合把降噪和续航放在同一优先级的人。', image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #dce5f9, #f4f0e7)', url: 'https://www.amazon.com/s?k=Sony+WH-1000XM5' },
  { id: 'bose-qc-ultra', title: 'Bose QuietComfort Ultra 头戴式耳机', brand: 'Bose', model: 'QC Ultra', platform: 'Lazada', tone: 'lazada', market: '新加坡 · SG', nativePrice: 'SGD 399.00', rmbPrice: 2118, fx: '1 SGD = 5.3083 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '8 分钟前更新', rating: 4.7, reviews: 863, stock: '有货', specs: ['沉浸式音频', '续航 24 小时', 'Bluetooth 5.1'], why: '降噪取向突出，商品价接近预算。', tradeoff: '适合优先考虑沉浸式降噪体验的人。', image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e9dfd2, #f5f3ef)', url: 'https://www.lazada.sg/catalog/?q=Bose%20QuietComfort%20Ultra' },
  { id: 'sennheiser-m4', title: 'Sennheiser Momentum 4 Wireless', brand: 'Sennheiser', model: 'Momentum 4', platform: 'Best Buy', tone: 'bestbuy', market: '美国 · US', nativePrice: 'USD 329.95', rmbPrice: 2378, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '12 分钟前更新', rating: 4.6, reviews: 516, stock: '库存有限', specs: ['自适应降噪', '续航 60 小时', 'Bluetooth 5.2'], why: '60 小时续航明显领先。', tradeoff: '适合把长续航放在首位的人。', image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e5e0d4, #eef2f5)', url: 'https://www.bestbuy.com/site/searchpage.jsp?st=Sennheiser+Momentum+4' },
  { id: 'soundcore-q45', title: 'Soundcore Space Q45 降噪耳机', brand: 'Soundcore', model: 'Space Q45', platform: 'Amazon', tone: 'amazon', market: '美国 · US', nativePrice: 'USD 149.99', rmbPrice: 1078, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '18 分钟前更新', rating: 4.4, reviews: 3210, stock: '暂无库存信息', specs: ['主动降噪', '续航 50 小时', 'LDAC'], why: '商品参考价最低，续航较长。', tradeoff: '适合优先控制商品预算的人。', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e8ecf3, #eee7e1)', url: 'https://www.amazon.com/s?k=Soundcore+Space+Q45' },
  { id: 'dell-u2723qe', title: 'Dell UltraSharp U2723QE 27 英寸 4K 显示器', brand: 'Dell', model: 'U2723QE', platform: 'Amazon', tone: 'amazon', market: '美国 · US', nativePrice: 'USD 579.99', rmbPrice: 4170, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '5 分钟前更新', rating: 4.7, reviews: 932, stock: '有货', specs: ['27 英寸 4K IPS', 'USB-C 90W', 'HDR 400'], why: '4K 清晰度与办公接口都齐备。', tradeoff: '适合把屏幕素质放在首位的人。', image: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e4e8f0, #f2efe8)', url: 'https://www.amazon.com/s?k=Dell+U2723QE' },
  { id: 'lg-27ul550', title: 'LG 27UL550-W 27 英寸 4K 显示器', brand: 'LG', model: '27UL550-W', platform: 'Best Buy', tone: 'bestbuy', market: '美国 · US', nativePrice: 'USD 299.99', rmbPrice: 2157, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '10 分钟前更新', rating: 4.5, reviews: 641, stock: '有货', specs: ['27 英寸 4K IPS', 'HDR 10', 'HDMI ×2'], why: '4K 门槛价最低，办公与观影都够用。', tradeoff: '适合预算优先的 4K 需求。', image: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e8eef5, #eee9e2)', url: 'https://www.bestbuy.com/site/searchpage.jsp?st=LG+27UL550' },
  { id: 'dell-s2722qc', title: 'Dell S2722QC 27 英寸 4K USB-C 显示器', brand: 'Dell', model: 'S2722QC', platform: 'Lazada', tone: 'lazada', market: '新加坡 · SG', nativePrice: 'SGD 539.00', rmbPrice: 2861, fx: '1 SGD = 5.3083 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '15 分钟前更新', rating: 4.6, reviews: 512, stock: '库存有限', specs: ['27 英寸 4K IPS', 'USB-C 65W', 'HDR 400'], why: '4K + USB-C 一线连接，价格居中。', tradeoff: '适合笔记本一线连屏的用户。', image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e5e7ef, #f1ece2)', url: 'https://www.lazada.sg/catalog/?q=Dell%20S2722QC' },
  { id: 'salomon-x-ultra-4', title: 'Salomon X Ultra 4 GTX 防水徒步鞋', brand: 'Salomon', model: 'X Ultra 4 GTX', platform: 'Amazon', tone: 'amazon', market: '美国 · US', nativePrice: 'USD 169.95', rmbPrice: 1222, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '6 分钟前更新', rating: 4.7, reviews: 1108, stock: '有货', specs: ['GORE-TEX 防水', 'Contagrip 抓地', '轻量支撑'], why: '防水与抓地均衡，适合轻装徒步。', tradeoff: '适合大部分入门徒步路线。', image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e7e3da, #eef0ea)', url: 'https://www.amazon.com/s?k=Salomon+X+Ultra+4+GTX' },
  { id: 'merrell-moab-3', title: 'Merrell Moab 3 防水徒步鞋', brand: 'Merrell', model: 'Moab 3', platform: 'Lazada', tone: 'lazada', market: '新加坡 · SG', nativePrice: 'SGD 159.00', rmbPrice: 844, fx: '1 SGD = 5.3083 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '11 分钟前更新', rating: 4.6, reviews: 748, stock: '有货', specs: ['防水皮革', 'Vibram 鞋底', '缓震中底'], why: '价格亲民，缓震与透气兼顾。', tradeoff: '适合注重性价比的日常徒步。', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e8e2e6, #f0ece7)', url: 'https://www.lazada.sg/catalog/?q=Merrell%20Moab%203' },
  { id: 'columbia-crestwood', title: 'Columbia Crestwood 轻便徒步鞋', brand: 'Columbia', model: 'Crestwood', platform: 'Amazon', tone: 'amazon', market: '美国 · US', nativePrice: 'USD 99.95', rmbPrice: 719, fx: '1 USD = 7.1882 CNY', fxAsOf: '更新于 2026-08-15 14:32', updated: '19 分钟前更新', rating: 4.4, reviews: 2260, stock: '暂无库存信息', specs: ['抓地外底', '缓震中底', '轻量鞋身'], why: '同品类里商品参考价最低。', tradeoff: '适合预算优先的户外需求。', image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80', gradient: 'linear-gradient(135deg, #e4eaef, #eee9e3)', url: 'https://www.amazon.com/s?k=Columbia+Crestwood' },
]

function Icon({ name, size = 18 }: { name: IconName; size?: number }) { const common = { width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, 'aria-hidden': true }; const paths: Record<IconName, ReactNode> = { arrow: <><path d="M5 12h13" /><path d="m13 6 6 6-6 6" /></>, check: <path d="m5 12 4 4L19 6" />, chevron: <path d="m6 9 6 6 6-6" />, close: <><path d="m6 6 12 12" /><path d="m18 6-12 12" /></>, external: <><path d="M14 5h5v5" /><path d="M10 14 19 5" /><path d="M19 14v4a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h4" /></>, filter: <><path d="M4 6h16" /><path d="M7 12h10" /><path d="M10 18h4" /></>, grid: <><rect x="4" y="4" width="6" height="6" rx="1" /><rect x="14" y="4" width="6" height="6" rx="1" /><rect x="4" y="14" width="6" height="6" rx="1" /><rect x="14" y="14" width="6" height="6" rx="1" /></>, info: <><circle cx="12" cy="12" r="9" /><path d="M12 11v5" /><path d="M12 8h.01" /></>, plus: <><path d="M12 5v14" /><path d="M5 12h14" /></>, search: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" /></>, spark: <path d="m12 3-1.5 5.5L5 10l5.5 1.5L12 17l1.5-5.5L19 10l-5.5-1.5L12 3Z" />, star: <path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9L12 3Z" />, target: <><circle cx="12" cy="12" r="8" /><circle cx="12" cy="12" r="4" /><circle cx="12" cy="12" r="1" /></> }; return <svg {...common}>{paths[name]}</svg> }
function Button({ children, onClick, icon, variant = 'secondary', disabled, type = 'button' }: { children: ReactNode; onClick?: () => void; icon?: IconName; variant?: 'primary' | 'secondary' | 'quiet'; disabled?: boolean; type?: 'button' | 'submit' }) { return <button className={`button button-${variant}`} type={type} onClick={onClick} disabled={disabled}>{children}{icon && <Icon name={icon} size={15} />}</button> }
function Mark({ product }: { product: Product }) { return <span className={`platform-mark ${product.tone}`}>{product.platform === 'Best Buy' ? 'BB' : product.platform[0]}</span> }
function budgetText(mission: Mission) { return mission.budget ? `¥${mission.budget.toLocaleString()} 内` : '未设置预算' }
function preferenceText(preference: Preference) { return preference === 'battery' ? '优先续航' : preference === 'noise' ? '优先降噪' : preference === 'lowest' ? '按商品价' : '综合推荐' }
type ProductCategory = 'headphones' | 'monitors' | 'shoes'
function intentCategory(intent: string): ProductCategory | null { if (/(耳机|降噪|headphone)/i.test(intent)) return 'headphones'; if (/(显示器|monitor|4k|屏幕)/i.test(intent)) return 'monitors'; if (/(徒步鞋|运动鞋|跑鞋|登山鞋|鞋)/i.test(intent)) return 'shoes'; return null }
function productCategory(product: Product): ProductCategory { return /(sony-xm5|bose-qc-ultra|sennheiser-m4|soundcore-q45)/.test(product.id) ? 'headphones' : /(显示器|monitor)/i.test(product.title) ? 'monitors' : 'shoes' }
function supportsIntent(intent: string) { return intentCategory(intent) !== null }
function supportsAudioPriorities(mission: Mission) { return intentCategory(mission.intent) === 'headphones' }
function stripBudget(text: string) { return text.replace(/(?:预算|不超过|到|改为)\s*[¥￥]?\s*\d{1,3}(?:,\d{3})*\s*(?:元|块|人民币|rmb)?\s*(?:以内|之内)?/gi, '').replace(/[¥￥]\s*\d{1,3}(?:,\d{3})*\s*(?:元|块|人民币|rmb)?\s*(?:以内|之内)?/gi, '').replace(/\d{1,3}(?:,\d{3})*\s*(?:元|块|人民币|rmb)\s*(?:以内|之内)?/gi, '') }
function parseBudgetCNY(text: string) { const s = text.replace(/,/g, ''); const m = s.match(/(?:预算|不超过|到|改为)?\s*[¥￥]?\s*(\d{3,6})\s*(?:元|块|人民币|rmb)/i) ?? s.match(/[¥￥]\s*(\d{3,6})/) ?? s.match(/(?:预算|不超过|到|改为)\s*(\d{3,6})/); const n = m ? Number(m[1]) : NaN; return Number.isFinite(n) && n >= 100 ? n : undefined }
function extractIntent(text: string) { const trimmed = stripBudget(text).replace(/^(?:帮我找|帮我买|帮我挑|帮我|我想买|我要买|我要找|我想|想买|请帮我|给我|要买|买|找)\s*/gi, '').replace(/^一[副个台件双只]\s*/gi, '').replace(/优先\s*(续航|降噪)|只看有货|仅看有货|最低商品价|低价/gi, '').replace(/[，,。；;]+/g, ' ').trim(); return trimmed || '未命名购物任务' }
function parsePreference(text: string): Preference { return /优先\s*续航/.test(text) ? 'battery' : /优先\s*降噪/.test(text) ? 'noise' : /最低商品价|低价优先|价格优先/.test(text) ? 'lowest' : 'balanced' }
function createMission(query: string, id: number): Mission { return { id, intent: extractIntent(query), budget: parseBudgetCNY(query), preference: parsePreference(query), onlyInStock: /只看有货|仅看有货/.test(query), version: 1 } }
function phaseText(phase: TaskPhase, selected: string[]) { return phase === 'comparing' ? `比较中 · ${selected.length} 件` : selected.length ? `已选 ${selected.length} 件` : phase === 'shortlisting' ? '继续选择候选' : '查看候选' }
function nowText() { return new Intl.DateTimeFormat('zh-CN', { hour: '2-digit', minute: '2-digit' }).format(new Date()) }
function batteryHours(product: Product) { return Number(product.specs.find((spec) => spec.includes('续航'))?.match(/\d+/)?.[0] ?? 0) }
function candidatesFor(mission: Mission) { const category = intentCategory(mission.intent); let list = category ? products.filter((product) => productCategory(product) === category) : []; if (mission.onlyInStock) list = list.filter((product) => product.stock === '有货'); return list.sort((a, b) => { if (category === 'headphones' && mission.preference === 'battery') return batteryHours(b) - batteryHours(a) || a.rmbPrice - b.rmbPrice; if (category === 'headphones' && mission.preference === 'noise') return Number(b.brand === 'Bose') - Number(a.brand === 'Bose') || a.rmbPrice - b.rmbPrice; if (mission.preference === 'lowest') return a.rmbPrice - b.rmbPrice; const budget = mission.budget; const aBudget = budget !== undefined ? Number(a.rmbPrice > budget) : 0; const bBudget = budget !== undefined ? Number(b.rmbPrice > budget) : 0; return aBudget - bBudget || b.rating - a.rating }) }
function eligibleFor(mission: Mission) { const candidates = candidatesFor(mission); const budget = mission.budget; return budget !== undefined ? candidates.filter((product) => product.rmbPrice <= budget) : candidates }

function Header({ view, go }: { view: View; go: (view: View) => void }) { return <header className="topbar"><button className="brand-lockup" onClick={() => go('home')}><span className="brand-mark">ir</span><span><strong>跨境选物台</strong><small>商品发现与比较</small></span></button><nav className="main-nav"><button className={view === 'home' ? 'is-active' : ''} onClick={() => go('home')}><Icon name="plus" size={15} />新建任务</button><button className={view === 'tasks' || view === 'discover' || view === 'compare' ? 'is-active' : ''} onClick={() => go('tasks')}><Icon name="spark" size={15} />我的任务</button></nav><div className="topbar-actions"><span className="currency-lock">比较货币 <b>RMB</b></span></div></header> }
function Home({ start }: { start: (query: string) => void }) { const [query, setQuery] = useState('帮我找一副适合通勤的降噪耳机，预算 2500 元以内'); const prompts = ['适合远程办公的 27 寸 4K 显示器，¥3,000 以内', '送给爸爸的轻便徒步鞋，¥1,000 以内', '降噪耳机，¥2,000 以内，优先续航']; return <main className="home-view"><div className="home-hero"><h1>想买什么？</h1><p>耳机、27 寸 4K 显示器和轻便徒步鞋均可比较。告诉我用途、预算和偏好，我会整理不同平台的商品价与证据。</p></div><form className="mission-composer" onSubmit={(event) => { event.preventDefault(); start(query) }}><div className="composer-label">描述你的需求</div><textarea value={query} onChange={(event) => setQuery(event.target.value)} rows={3} aria-label="描述购物需求" /><div className="composer-footer"><span>商品价换算为 RMB；运费与税费以商户结算页为准</span><Button variant="primary" type="submit" icon="arrow" disabled={!query.trim()}>开始比较</Button></div></form><div className="prompt-row"><span>试试这样说</span>{prompts.map((prompt) => <button key={prompt} type="button" onClick={() => setQuery(prompt)}>{prompt}</button>)}</div><section className="home-preview" aria-label="比较示意"><div className="preview-heading"><span>比较示意</span><strong>通勤降噪耳机 · ¥2,500 内</strong><small>商品价估算 · 未含运费与税费</small></div><div className="preview-rows" aria-label="示例比较结果"><div className="preview-row"><span className="platform-mark amazon">A</span><b>Amazon US</b><strong>USD 299</strong><em>约 ¥2,149</em></div><div className="preview-row"><span className="platform-mark lazada">L</span><b>Lazada SG</b><strong>SGD 399</strong><em>约 ¥2,118</em></div><div className="preview-row"><span className="platform-mark bestbuy">BB</span><b>Best Buy US</b><strong>USD 329</strong><em>约 ¥2,368</em></div></div><div className="preview-foot"><span>已统一商品价口径，可继续比较规格与评价</span><span>费用以商户结算页为准</span></div></section><div className="home-capability-summary">多平台候选 · 商品价换算 · 规格与评价比较</div></main> }
function PriceEvidence({ product, compact = false }: { product: Product; compact?: boolean }) { return <div className={`price-evidence ${compact ? 'compact' : ''}`}><div><strong>约 ¥{product.rmbPrice.toLocaleString()}</strong><span>{product.nativePrice}</span></div><small>{product.fx} · {product.fxAsOf}</small><small>{compact ? '商品价估算 · 运费与税费待商户结算确认' : `${product.updated} · 商品价估算，运费与税费以商户结算页为准`}</small></div> }
function Brief({ mission }: { mission: Mission }) { return <section className="mission-brief" aria-label="当前任务条件"><div className="brief-filters"><span className="brief-condition brief-condition-primary">{mission.intent}</span><span className="brief-condition">预算 {budgetText(mission)}</span><span className="brief-condition">{preferenceText(mission.preference)}</span>{mission.onlyInStock && <span className="brief-condition">仅看有货</span>}</div></section> }
function EvidenceStrip({ candidates }: { candidates: Product[] }) { if (!candidates.length) return null; const sources = [...new Set(candidates.map((product) => `${product.platform} ${product.market.split('·')[1]?.trim() ?? ''}`))].join('、'); const fxTime = candidates[0].fxAsOf.match(/\d{2}:\d{2}/)?.[0]; return <section className="evidence-strip"><div><Icon name="search" size={15} /><span><b>已检索</b> {sources}</span></div><div><Icon name="info" size={15} /><span><b>价格口径</b> 商品价估算；运费与税费未计入</span></div><div><Icon name="info" size={15} /><span><b>商品与汇率</b> {fxTime ? `更新于 ${fxTime}` : candidates[0].fxAsOf}</span></div></section> }
function ChangeSummary({ change, undo }: { change: ChangeRecord | null; undo: () => void }) { if (!change) return null; return <section className="change-summary" aria-live="polite"><div><strong>本次变更</strong><p>{change.summary} · 候选 {change.resultBefore} → {change.resultAfter}</p></div><button onClick={undo}>撤销本次修改</button></section> }

function Conversation({ mission, apply, compare, canCompare, comparing = false, messages, append, latestChange, undo }: { mission: Mission; apply: (delta: Partial<Mission>, summary: string) => void; compare: () => void; canCompare: boolean; comparing?: boolean; messages: Message[]; append: (items: Message[]) => void; latestChange: ChangeRecord | null; undo: () => void }) {
  const [draft, setDraft] = useState('')
  const action = (name: string) => {
    if (name === '比较已选候选') { if (canCompare) compare(); else append([{ id: String(Date.now()), role: 'agent', text: '先加入两件候选，再开始对比。' }]); return }
    const preference: Preference = name === '优先降噪' ? 'noise' : name === '优先续航' ? 'battery' : name === '按商品价排序' ? 'lowest' : 'balanced'
    apply({ preference }, `排序：${preferenceText(preference)}`)
    append([{ id: `u-${Date.now()}`, role: 'user', text: name }, { id: `a-${Date.now()}`, role: 'agent', text: `已将推荐依据改为“${preferenceText(preference)}”。价格仍是商品价估算，运费和税费请以商户结算页为准。` }])
  }
  const submit = (event?: FormEvent) => {
    event?.preventDefault(); const text = draft.trim(); if (!text) return
    const budget = parseBudgetCNY(text); const onlyInStock = /只看有货|仅看有货/.test(text); const preference = parsePreference(text)
    const requestedIntent = extractIntent(text); const explicitIntent = /(?:换成|改找|我想买|帮我找|找一[副个台件]|显示器|徒步鞋|耳机)/.test(text) && supportsIntent(requestedIntent)
    const delta: Partial<Mission> = {}; const parts: string[] = []
    if (budget) { delta.budget = budget; parts.push(`预算 ¥${budget.toLocaleString()} 内`) }
    if (onlyInStock) { delta.onlyInStock = true; parts.push('仅看有货') }
    if (preference !== 'balanced') { delta.preference = preference; parts.push(`排序：${preferenceText(preference)}`) }
    if (explicitIntent) { delta.intent = requestedIntent; if (!supportsAudioPriorities({ ...mission, intent: requestedIntent })) delta.preference = preference === 'battery' || preference === 'noise' ? 'balanced' : preference; parts.push(`商品：${requestedIntent}`) }
    append([{ id: `u-${Date.now()}`, role: 'user', text }])
    if (parts.length) { apply(delta, parts.join(' · ')); append([{ id: `a-${Date.now()}`, role: 'agent', text: `已更新${parts.join('、')}。我只会按已识别的条件重排；商品价均未包含运费和税费。` }]) }
    else append([{ id: `a-${Date.now()}`, role: 'agent', text: `我还不能用“${text}”改变排序，因为当前候选没有对应的可比字段。你可以调整预算、库存、商品类别，或选择可用的排序条件。` }])
    setDraft('')
  }
  const audioActions = supportsAudioPriorities(mission) ? ['优先降噪', '优先续航', '先看综合推荐'] : ['按商品价排序', '先看综合推荐']
  return <aside className={`conversation-panel ${messages.length <= 1 ? 'is-brief' : ''}`}><div className="conversation-header"><div><span>选购助手</span></div></div><Brief mission={mission} /><ChangeSummary change={latestChange} undo={undo} /><div className="conversation-thread" aria-label="任务对话">{messages.map((message) => <div className={`conversation-message ${message.role}`} key={message.id}><div className="message-meta">{message.role === 'user' ? '你' : '选购助手'}</div><p>{message.text}</p>{message.actions && <div className="message-actions">{message.actions.map((name) => <button key={name} onClick={() => action(name)}>{name}</button>)}</div>}</div>)}</div><div className="conversation-suggestions">{audioActions.map((name) => <button key={name} onClick={() => action(name)}>{name}</button>)}<button onClick={() => apply({ onlyInStock: !mission.onlyInStock }, mission.onlyInStock ? '库存：显示全部' : '库存：仅看有货')}>{mission.onlyInStock ? '显示全部库存' : '只看有货'}</button>{!comparing && <button onClick={() => action('比较已选候选')}>对比已选</button>}</div><form className="conversation-composer" onSubmit={submit}><textarea rows={2} value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="例如：预算改为 ¥2000，或只看有货" aria-label="选购对话输入" /><div className="composer-row"><button className="send-button" disabled={!draft.trim()} aria-label="发送"><Icon name="arrow" size={16} /></button></div></form></aside>
}
function CandidateCard({ product, selected, toggle, detail, budget, preference }: { product: Product; selected: boolean; toggle: () => void; detail: () => void; budget?: number; preference: Preference }) {
  const reason = preference === 'battery' && batteryHours(product) ? `续航 ${batteryHours(product)} 小时${product.id === 'sennheiser-m4' ? '，当前候选中最长。' : '。'}` : preference === 'noise' && product.brand === 'Bose' ? '降噪取向与当前偏好一致。' : preference === 'lowest' ? '当前按商品参考价由低至高排列。' : product.why
  return <article className={`product-card evidence-card ${selected ? 'is-selected' : ''}`}>
    <button className="product-image-button" onClick={detail}><div className="product-image" style={{ background: product.gradient }}><img src={product.image} alt="" /><span className="image-tag">{product.stock}</span></div></button>
    <div className="product-card-body"><div className="product-source"><span><Mark product={product} /> {product.platform}</span><span>{product.market}</span></div><button className="product-title" onClick={detail}>{product.title}</button><div className="rating-line"><span className="stars"><Icon name="star" size={13} /> {product.rating}</span><span>{product.reviews.toLocaleString()} 条评价</span></div><PriceEvidence product={product} compact /><div className="spec-line">{product.specs.slice(0, 2).map((spec) => <span key={spec}>{spec}</span>)}</div><p className="candidate-reason"><b>为什么排在这里</b>{reason}</p>{budget && product.rmbPrice > budget && <p className="budget-warning">超出预算 ¥{(product.rmbPrice - budget).toLocaleString()}</p>}<div className="card-bottom"><span className={product.stock === '有货' ? 'stock confirmed' : 'stock pending'}>{product.stock}</span><Button variant={selected ? 'primary' : 'secondary'} onClick={toggle} icon={selected ? 'check' : 'plus'}>{selected ? '已加入候选' : '加入候选'}</Button></div></div>
  </article>
}
function Decision({ candidates, mission }: { candidates: Product[]; mission: Mission }) { const product = candidates[0]; if (!product) return null; const explanation = mission.preference === 'battery' && batteryHours(product) ? `续航 ${batteryHours(product)} 小时，是当前可推荐候选中最长的。` : mission.preference === 'noise' && product.brand === 'Bose' ? '它的降噪取向与当前偏好最一致。' : mission.preference === 'lowest' ? '它是当前可推荐候选中商品参考价最低的一件。' : product.why; return <section className="decision-card"><div className="decision-icon"><Icon name="spark" size={20} /></div><div><span>当前推荐</span><h2>{product.brand} {product.model}</h2><p>{explanation} {product.tradeoff}</p><div className="decision-tags">{[mission.budget ? '商品价在预算内' : '未设置预算', mission.onlyInStock ? '当前有货' : '库存已列出', preferenceText(mission.preference)].map((tag) => <span key={tag}>{tag}</span>)}</div></div></section> }
function Discover({ mission, apply, selectedIds, toggle, compare, detail, messages, append, latestChange, undo }: { mission: Mission; apply: (delta: Partial<Mission>, summary: string) => void; selectedIds: string[]; toggle: (id: string) => void; compare: () => void; detail: (product: Product) => void; messages: Message[]; append: (items: Message[]) => void; latestChange: ChangeRecord | null; undo: () => void }) {
  const candidates = useMemo(() => candidatesFor(mission), [mission])
  const recommended = useMemo(() => eligibleFor(mission), [mission])
  const selected = products.filter((product) => selectedIds.includes(product.id))
  const platformCount = new Set(candidates.map((product) => product.platform)).size
  const unsupported = !supportsIntent(mission.intent)
  const hasTemporaryFilters = mission.preference !== 'balanced' || mission.onlyInStock
  const resetFilters = () => apply({ preference: 'balanced', onlyInStock: false }, '已重置筛选与排序')

  return (
    <main className="workspace-view">
      <div className="mission-header">
        <div>
          <div className="breadcrumb">我的任务 <Icon name="chevron" size={13} />推荐候选</div>
          <h1>{mission.intent}</h1>
          <div className="mission-subline"><span>{candidates.length ? '候选已就绪' : '等待补充条件'}</span>{candidates.length > 0 && <span>{candidates.length} 个候选{candidates.length === 1 ? '' : ` · ${platformCount} 个平台`}</span>}</div>
        </div>
      </div>
      <div className="workspace-layout">
        <Conversation mission={mission} apply={apply} compare={compare} canCompare={selected.length >= 2} messages={messages} append={append} latestChange={latestChange} undo={undo} />
        <section className="results-region">
          <EvidenceStrip candidates={candidates} />
          {unsupported ? (
            <section className="empty-result">
              <Icon name="search" size={24} />
              <h2>暂未找到可比较的商品</h2>
              <p>目前可比较耳机、27 寸 4K 显示器和轻便徒步鞋。请修改商品描述后继续。</p>
              <Button onClick={() => apply({ intent: '通勤降噪耳机' }, '商品：通勤降噪耳机')}>查看耳机候选</Button>
            </section>
          ) : (
            <>
              {recommended.length ? (
                <Decision candidates={recommended} mission={mission} />
              ) : (
                <section className="empty-result">
                  <Icon name="search" size={24} />
                  <h2>预算内暂无符合条件的候选</h2>
                  <p>候选已按当前条件展示；可以提高预算、调整偏好或显示全部库存。</p>
                  <Button onClick={() => apply({ onlyInStock: false }, '库存：显示全部')}>显示全部库存</Button>
                </section>
              )}
              <div className="filter-bar">
                <div className="result-count"><strong>{candidates.length}</strong> 个候选 {platformCount > 0 && <span>· {platformCount} 个平台</span>}</div>
                <div className="filter-actions">
                  <button onClick={() => apply({ onlyInStock: !mission.onlyInStock }, mission.onlyInStock ? '库存：显示全部' : '库存：仅看有货')}><Icon name="filter" size={15} />{mission.onlyInStock ? '显示全部库存' : '只看有货'}</button>
                  <select value={mission.preference} onChange={(event) => apply({ preference: event.target.value as Preference }, `排序：${preferenceText(event.target.value as Preference)}`)} aria-label="候选排序">
                    <option value="balanced">综合推荐</option>
                    <option value="lowest">按商品价</option>
                    {supportsAudioPriorities(mission) && <><option value="noise">优先降噪</option><option value="battery">优先续航</option></>}
                  </select>
                  {mission.preference !== 'balanced' && <button className="active-filter-chip" onClick={() => apply({ preference: 'balanced' }, '排序：综合推荐')} aria-label={`移除${preferenceText(mission.preference)}排序`}>{preferenceText(mission.preference)} <Icon name="close" size={13} /></button>}
                  {mission.onlyInStock && <button className="active-filter-chip" onClick={() => apply({ onlyInStock: false }, '库存：显示全部')} aria-label="移除仅看有货筛选">只看有货 <Icon name="close" size={13} /></button>}
                  {hasTemporaryFilters && <><span className="filter-divider" aria-hidden="true" /><button className="clear-filters-button" onClick={resetFilters} title="恢复为综合推荐，并显示全部库存；不会修改商品需求、预算或已选候选">清除筛选</button></>}
                </div>
              </div>
              <section className="product-results">
                <div className="products-grid">
                  {candidates.map((product) => <CandidateCard key={product.id} product={product} selected={selectedIds.includes(product.id)} toggle={() => toggle(product.id)} detail={() => detail(product)} budget={mission.budget} preference={mission.preference} />)}
                </div>
              </section>
            </>
          )}
        </section>
      </div>
      {selected.length > 0 && <div className="compare-tray">
        <div><span className="tray-count">{selected.length}</span><strong>已选候选</strong><small>最多 5 件</small></div>
        <div className="tray-items">{selected.map((product) => <button key={product.id} onClick={() => toggle(product.id)}>{product.brand} · 约 ¥{product.rmbPrice.toLocaleString()} <Icon name="close" size={13} /></button>)}</div>
        <Button variant="primary" onClick={compare} disabled={selected.length < 2} icon="arrow">开始对比</Button>
      </div>}
    </main>
  )
}
function Compare({ mission, selectedIds, back, detail, apply, messages, append, latestChange, undo }: { mission: Mission; selectedIds: string[]; back: () => void; detail: (product: Product) => void; apply: (delta: Partial<Mission>, summary: string) => void; messages: Message[]; append: (items: Message[]) => void; latestChange: ChangeRecord | null; undo: () => void }) {
  const items = products.filter((product) => selectedIds.includes(product.id))
  if (items.length < 2) return <main className="workspace-view"><section className="empty-result"><Icon name="grid" size={24} /><h2>还需要至少 2 件候选</h2><p>先在候选页加入商品，再进行横向比较。</p><Button variant="primary" onClick={back}>返回候选页</Button></section></main>
  const lead = candidatesFor(mission).filter((product) => selectedIds.includes(product.id))[0]
  const explanation = mission.preference === 'battery' && batteryHours(lead) ? `续航 ${batteryHours(lead)} 小时，是已选商品中最长的。` : mission.preference === 'noise' && lead.brand === 'Bose' ? '降噪取向与当前偏好最一致。' : `商品参考价约 ¥${lead.rmbPrice.toLocaleString()}，是已选商品中更低的一件。`
  return <main className="workspace-view compare-view"><div className="mission-header"><div><div className="breadcrumb"><button onClick={back}>推荐候选</button><Icon name="chevron" size={13} />对比选择</div><h1>在 {items.length} 个候选中做决定</h1><div className="mission-meta"><span>任务 V{mission.version}</span><span>继续提问可更新推荐</span></div></div><Button onClick={back} icon="plus">添加候选</Button></div><div className="workspace-layout"><Conversation mission={mission} apply={apply} compare={() => {}} canCompare={true} comparing messages={messages} append={append} latestChange={latestChange} undo={undo} /><section className="results-region"><section className="decision-card compare-decision"><div className="decision-icon"><Icon name="spark" size={20} /></div><div><span>当前推荐</span><h2>{lead.brand} {lead.model}</h2><p>{explanation}</p><small className="decision-boundary">推荐基于商品价与可见规格；运费、税费和配送资格请在商户结算页确认。</small></div></section><EvidenceStrip candidates={items} /><section className="comparison-table-wrap"><div className="table-toolbar"><span>已选商品对比</span><span>商品价估算，运费与税费以商户结算页为准</span></div><div className="comparison-table revised-table"><div className="comparison-label-column"><div>候选</div><div>商品价</div><div>规格</div><div>库存</div><div>适合谁</div><div>操作</div></div>{items.map((product) => <div className="comparison-product" key={product.id}><div className="comparison-product-head"><Mark product={product} /><button onClick={() => detail(product)}>{product.title}<Icon name="external" size={13} /></button></div><div className="compare-cell"><PriceEvidence product={product} compact /></div><div className="compare-cell specs-cell">{product.specs.map((spec) => <span key={spec}>{spec}</span>)}</div><div className="compare-cell"><span className={product.stock === '有货' ? 'confirmed' : 'pending'}>{product.stock}</span></div><div className="compare-cell"><span>{product.tradeoff}</span></div><div className="compare-cell action-cell"><Button onClick={() => detail(product)}>查看详情</Button></div></div>)}</div></section></section></div></main>
}
function Drawer({ product, selected, close, toggle }: { product: Product; selected: boolean; close: () => void; toggle: () => void }) { const domain = new URL(product.url).hostname; return <div className="drawer-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close() }}><aside className="product-drawer" aria-label="商品详情"><div className="drawer-top"><span>商品详情</span><button className="icon-button" onClick={close} aria-label="关闭"><Icon name="close" size={18} /></button></div><div className="drawer-image" style={{ background: product.gradient }}><img src={product.image} alt={product.title} /></div><div className="drawer-body"><div className="product-source"><span><Mark product={product} /> {product.platform}</span><span>{product.market}</span></div><h2>{product.title}</h2><PriceEvidence product={product} /><section className="drawer-section"><div className="section-title">商品信息</div><div className="spec-pills">{product.specs.map((spec) => <span key={spec}>{spec}</span>)}</div><p className="drawer-description">评分 {product.rating} · {product.reviews.toLocaleString()} 条评价 · 库存：{product.stock} · {product.updated}</p></section><section className="purchase-check"><span>查看商户报价</span><p>本服务只负责比较；{domain} 将提供商品详情与交易。</p><a className="button button-primary merchant-link" href={product.url} target="_blank" rel="noreferrer">前往 {product.platform} 查看<Icon name="external" size={15} /></a><small>商品价以商户页面为准。</small></section></div><div className="drawer-footer"><Button variant={selected ? 'primary' : 'secondary'} onClick={toggle}>{selected ? '已加入候选' : '加入候选'}</Button><Button variant="quiet" onClick={close}>返回任务</Button></div></aside></div> }
function TaskList({ tasks, activeId, open, create }: { tasks: ShoppingTask[]; activeId: number | null; open: (id: number) => void; create: () => void }) { return <main className="task-list-view"><div className="task-list-header"><div><h1>我的任务</h1><p>每个任务保留自己的对话、条件、候选与比较进度。</p></div><Button variant="primary" onClick={create} icon="plus">新建任务</Button></div>{tasks.length ? <section className="task-list" aria-label="已保存的选购任务">{tasks.map((task) => <button className={`task-list-item ${task.id === activeId ? 'is-current' : ''}`} key={task.id} onClick={() => open(task.id)}><div><strong>{task.mission.intent}</strong><p>{budgetText(task.mission)} · {preferenceText(task.mission.preference)}{task.mission.onlyInStock ? ' · 仅看有货' : ''}</p></div><div className="task-list-meta"><span>{task.id === activeId ? '当前处理' : phaseText(task.phase, task.selected)}</span><small>{task.updatedAt} 更新</small></div><Icon name="arrow" size={16} /></button>)}</section> : <section className="task-list-empty"><Icon name="spark" size={24} /><h2>还没有选购任务</h2><p>新建一个任务后，可以随时在这里继续对话和比较。</p><Button variant="primary" onClick={create}>新建任务</Button></section>}</main> }
function QuickSwitcher({ tasks, activeId, open, close, allTasks, create }: { tasks: ShoppingTask[]; activeId: number | null; open: (id: number) => void; close: () => void; allTasks: () => void; create: () => void }) { const [query, setQuery] = useState(''); const items = [...tasks].sort((a, b) => b.updatedAtMs - a.updatedAtMs).filter((task) => `${task.mission.intent} ${budgetText(task.mission)} ${preferenceText(task.mission.preference)}${task.mission.onlyInStock ? ' 仅看有货' : ''}`.includes(query.trim())); return <div className="switcher-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close() }}><section className="task-switcher" role="dialog" aria-modal="true" aria-label="切换任务"><div className="switcher-heading"><div><strong>切换任务</strong><small>将恢复各任务上次的工作现场</small></div><button onClick={close} aria-label="关闭任务切换"><Icon name="close" size={16} /></button></div><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索任务名称、预算或偏好" aria-label="搜索任务" />{items.length ? <div className="switcher-list">{items.slice(0, 6).map((task) => <button className={task.id === activeId ? 'is-current' : ''} key={task.id} onClick={() => open(task.id)}><span><b>{task.mission.intent}</b><small>{budgetText(task.mission)} · {preferenceText(task.mission.preference)}{task.mission.onlyInStock ? ' · 仅看有货' : ''} · {task.updatedAt}</small></span>{task.id === activeId && <em>当前</em>}</button>)}</div> : <p className="switcher-empty">未找到匹配的任务</p>}<div className="switcher-footer"><button onClick={allTasks}>查看全部任务</button><button onClick={create}>新建任务</button></div></section></div> }
export default function App() {
  const [view, setView] = useState<View>('home')
  const [tasks, setTasks] = useState<ShoppingTask[]>(() => { try { const saved = localStorage.getItem('interecagent.tasks'); const parsed = saved ? JSON.parse(saved) : []; return Array.isArray(parsed) ? parsed.map((task) => ({ ...task, phase: task.phase ?? (task.selected?.length ? 'shortlisting' : 'collecting'), lastSurface: task.lastSurface ?? 'discover', createdAt: task.createdAt ?? task.updatedAt ?? nowText(), updatedAt: task.updatedAt ?? nowText(), updatedAtMs: task.updatedAtMs ?? task.id ?? Date.now() })) : [] } catch { return [] } })
  const [activeTaskId, setActiveTaskId] = useState<number | null>(() => { try { const saved = localStorage.getItem('interecagent.active-task'); return saved ? Number(saved) : null } catch { return null } })
  const [detail, setDetail] = useState<Product | null>(null)
  const [switcherOpen, setSwitcherOpen] = useState(false)
  const activeTask = activeTaskId === null ? undefined : tasks.find((task) => task.id === activeTaskId)
  useEffect(() => { localStorage.setItem('interecagent.tasks', JSON.stringify(tasks)); if (activeTaskId !== null) localStorage.setItem('interecagent.active-task', String(activeTaskId)); else localStorage.removeItem('interecagent.active-task') }, [tasks, activeTaskId])
  const updateActive = (update: (task: ShoppingTask) => ShoppingTask) => { if (!activeTask) return; setTasks((current) => current.map((task) => task.id === activeTask.id ? update(task) : task).sort((a, b) => b.updatedAtMs - a.updatedAtMs)) }
  const append = (items: Message[]) => updateActive((task) => ({ ...task, messages: [...task.messages, ...items], updatedAt: nowText(), updatedAtMs: Date.now() }))
  const apply = (delta: Partial<Mission>, summary: string) => updateActive((task) => { const before = task.mission; const next = { ...before, ...delta, version: before.version + 1 }; const selected = next.onlyInStock ? task.selected.filter((id) => products.find((product) => product.id === id)?.stock === '有货') : task.selected; return { ...task, mission: next, selected, phase: selected.length >= 2 && task.lastSurface === 'compare' ? 'comparing' : selected.length ? 'shortlisting' : 'collecting', updatedAt: nowText(), updatedAtMs: Date.now(), latestChange: { id: String(Date.now()), summary, before, selectedBefore: task.selected, resultBefore: candidatesFor(before).length, resultAfter: candidatesFor(next).length } } })
  const undo = () => { if (!activeTask?.latestChange) return; const change = activeTask.latestChange; updateActive((task) => ({ ...task, mission: change.before, selected: change.selectedBefore, phase: change.selectedBefore.length >= 2 && task.lastSurface === 'compare' ? 'comparing' : change.selectedBefore.length ? 'shortlisting' : 'collecting', latestChange: null, updatedAt: nowText(), updatedAtMs: Date.now(), messages: [...task.messages, { id: `undo-${Date.now()}`, role: 'agent', text: `已撤销“${change.summary}”，恢复之前的条件。` }] })) }
  const start = (query: string) => { const id = Date.now(); const mission = createMission(query, id); const time = nowText(); const actions = supportsAudioPriorities(mission) ? ['优先降噪', '优先续航', '先看综合推荐'] : ['按商品价排序', '先看综合推荐']; const task: ShoppingTask = { id, mission, selected: [], latestChange: null, phase: 'collecting', lastSurface: 'discover', createdAt: time, updatedAt: time, updatedAtMs: id, messages: [{ id: `start-${id}`, role: 'agent', text: `已识别“${mission.intent}”${mission.budget ? `，商品价预算 ${budgetText(mission)}` : ''}。我先按综合推荐整理候选；接下来请告诉我最在意的排序条件。商品价已换算为 RMB，运费、税费和配送资格将在商户结算页确认。`, actions }] }; setTasks((current) => [task, ...current]); setActiveTaskId(id); setView('discover') }
  const openTask = (id: number) => { const task = tasks.find((item) => item.id === id); if (!task) return; setActiveTaskId(id); setSwitcherOpen(false); setView(task.lastSurface) }
  const toggle = (id: string) => updateActive((task) => { const selected = task.selected.includes(id) ? task.selected.filter((item) => item !== id) : task.selected.length >= 5 ? task.selected : [...task.selected, id]; return { ...task, selected, phase: selected.length ? 'shortlisting' : 'collecting', lastSurface: 'discover', updatedAt: nowText(), updatedAtMs: Date.now() } })
  const compare = () => { if (!activeTask || activeTask.selected.length < 2) return; updateActive((task) => ({ ...task, phase: 'comparing', lastSurface: 'compare', updatedAt: nowText(), updatedAtMs: Date.now() })); setView('compare') }
  const backToCandidates = () => { updateActive((task) => ({ ...task, phase: task.selected.length ? 'shortlisting' : 'collecting', lastSurface: 'discover', updatedAt: nowText(), updatedAtMs: Date.now() })); setView('discover') }
  return <div className="app-shell"><Header view={view} go={setView} />{activeTask && (view === 'discover' || view === 'compare') && <button className="quick-switch-trigger" onClick={() => setSwitcherOpen(true)}><span>当前任务</span><strong>{activeTask.mission.intent}</strong><Icon name="chevron" size={14} /></button>}{view === 'home' && <Home start={start} />}{view === 'tasks' && <TaskList tasks={[...tasks].sort((a, b) => b.updatedAtMs - a.updatedAtMs)} activeId={activeTaskId} open={openTask} create={() => setView('home')} />}{view === 'discover' && activeTask && <Discover mission={activeTask.mission} apply={apply} selectedIds={activeTask.selected} toggle={toggle} compare={compare} detail={setDetail} messages={activeTask.messages} append={append} latestChange={activeTask.latestChange} undo={undo} />}{view === 'compare' && activeTask && <Compare mission={activeTask.mission} selectedIds={activeTask.selected} back={backToCandidates} detail={setDetail} apply={apply} messages={activeTask.messages} append={append} latestChange={activeTask.latestChange} undo={undo} />}{detail && activeTask && <Drawer product={detail} selected={activeTask.selected.includes(detail.id)} close={() => setDetail(null)} toggle={() => toggle(detail.id)} />}{switcherOpen && <QuickSwitcher tasks={tasks} activeId={activeTaskId} open={openTask} close={() => setSwitcherOpen(false)} allTasks={() => { setSwitcherOpen(false); setView('tasks') }} create={() => { setSwitcherOpen(false); setView('home') }} />}</div>
}
